Fixed getOtherHalfOfChest bug, added JDocs
NRProjects/SMP pull request #19
Opened 2023-12-02 16:49 UTC by paulpugh000

Fixed a bug in the getOtherHalfofChest method where it would reach for the first chest it could find, going in the order of 
- NORTH
- EAST
- SOUTH
- WEST

instead of grabbing the actual other side of the double chest.
Added "Wax" particles and sound effect when a lock is successfully created, and the lock sign is now unable to be edited after being made.
Added light JDocs for methods that aren't the EventHandlers.

2023-12-02 23:30 UTC, Teelair requested changes
Mostly looks good, basically just nitpicks.

2023-12-02 23:30 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> +    private void signCreationParticles(World world, Location location, Particle particle) {
This method name isn't a verb, it's just `signCreationParticles` which seems more idiomatic of a variable name to me. This could benefit from a rename, maybe `showSignParticles` or something?

```suggestion
    private void showSignParticles(World world, Location location, Particle particle) {
```

2023-12-02 23:30 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> +    /**
Lint nitpick
```suggestion

    /**
```

2023-12-02 23:30 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> +    /**
Lint nitpick
```suggestion

    /**
```

2023-12-02 23:30 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> +    /**
Lint nitpick
```suggestion

    /**
```

2023-12-02 23:30 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> +    /**
Lint nitpick
```suggestion

    /**
```

2023-12-02 23:30 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> +        SMPUtils.log("Defaulted");
Hanging debug log here
```suggestion
```

2023-12-02 23:30 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> +     * Cancels an event and sends a message to the player */
Random note, and not your fault, this method seems weird. Future TODO: Remove this

2023-12-02 23:30 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> +//        If right clicked on storage container
Are these indents weird? Is GitHub showing it to me wrong?

2023-12-02 23:30 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> +//            If valid sign and doesn't have access
Are these indents weird? Is GitHub showing it to me wrong?

2023-12-02 23:30 UTC, Teelair commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> + // TODO: Prevent multiple people from placing lock signs on a single chest or double chest.
Are these indents weird? Is GitHub showing it to me wrong?

2023-12-03 00:04 UTC, paulpugh000 commented on src/main/java/plugins/nate/smp/listeners/ChestLockListener.java
> +        double z = signLocation.getZ();
The x, y, z variables are.

2023-12-03 20:38 UTC, NRProjects requested changes
You're main pull request comment is to vague. I'm not sure what is supposed to be tested, what the original state was and then what the fixed state is supposed to be

2023-12-03 20:56 UTC, NRProjects commented
Tested and merged

2023-12-03 20:57 UTC, NRProjects approved these changes

2023-12-03 20:58 UTC, merged

2023-12-03 20:58 UTC, Teelair commented
LBTY @NRProjects?