Fixed VeinMiner not dropping xp for blocks mined with VeinMiner
NRProjects/SMP pull request #47
Opened 2023-12-13 23:55 UTC by NRProjects

Fixes #33 

## Description
Fixes the veinminer xp bug by calculating the xp and dropping it manually since ```breakNaturally()``` and neither does ```dropItemNaturally()```
```breakBlockNaturally``` also doesn't calculate for fortune

Added JavaDocs

2023-12-14 09:29 UTC, Teelair commented
player#breakBlock(block)

2023-12-14 09:30 UTC, Teelair commented
This could be solved with `player.breakBlock(block)`. Also, you have a bunch of logging in here.

2023-12-14 15:45 UTC, NRProjects commented
> This could be solved with `player.breakBlock(block)`. Also, you have a bunch of logging in here. 

Forget to mention in the PR, but that doesn't drop XP, or calculate for fortune, or both. It was the first thing I tried and forgot to document why it didn't work

2023-12-14 17:06 UTC, paulpugh000 commented
Tested this method yesterday. It does work, it does drop the correct amount of XP. 
Here's my test I did:
Started off with this pickaxe, Fortune 3 Unbreaking 3, Vein Miner with the player.breakBlock(block) method used.
<img src="https://github.com/NRProjects/SMP/assets/76031490/fba0a28d-03b4-4650-9178-7a351af5f93b" width="200"/>
I used this 3x3x9, 54 blocks of Nether Quartz to see if the changes worked. Quartz drops a lot of XP, so I used it as the medium.
<img src="https://github.com/NRProjects/SMP/assets/76031490/cc480234-e04d-4a23-a713-f620af08da8b" width="200"/>
Here's the drops I got from using Vein Miner (crouching and mining)
<img src="https://github.com/NRProjects/SMP/assets/76031490/1e073f7b-da89-4d26-b0d0-8b631dde1ca5" width="200"/>
The method does work, and it solves the other pitfalls that weren't addressed here, such as not taking into account Fortune and Silk Touch. But because player.BreakBlock(block) does call a BlockBreakEvent, you need to make sure you aren't doing this recursively or you might get stack overflow. I think this might have happened in the cases you tested, but even when not adding the guard rails for recursion, it still drops the proper amount of XP, just not the items. (Until the server crashes)

2023-12-14 19:36 UTC, NRProjects commented
Yeah those were basically my findings. This would have to happen recursively since we would be calling it for every block stored in the set. Probably could solve the overflow issue by lowering the max amount of veinmineable blocks per veinmine but the way implemented in the PR solves the issue without limiting the user experience

2023-12-18 22:27 UTC, Teelair requested changes

2023-12-18 22:28 UTC, NRProjects commented on src/main/java/plugins/nate/smp/listeners/enchantments/VeinMinerListener.java
> +     */
I didnt star the comment train and I ain't got time to write javadocs

2023-12-22 09:56 UTC, Teelair approved these changes
LGTM! :shipit:

2023-12-22 09:58 UTC, merged