Created tellers to transfer diamonds into digital diamonds
NRProjects/SMP pull request #60
Opened 2023-12-30 21:54 UTC by paulpugh000

Added two new commands, they need the `smp.createteller` permission. 
- `/smp teller deposit` Creates a villager with a "Deposit diamonds" text above it. Right clicking it: takes a diamond from the players inventory and adds balance equal to the value of the diamond type. `DIAMOND_BLOCK`s get deposited first, then `DIAMOND`s. If a person is shift right clicking, it will deposit all the diamonds in their hand into the bank.

- `/smp teller withdraw` Creates a villager with a "Withdraw diamonds" text above it. Right clicking it will withdraw 1 `DIAMOND_BLOCK` if they have more than or equal to 9 virtual diamonds. If they have less than 9, it will give a `DIAMOND`.
Players are unable to withdraw if they have a full inventory.

2023-12-30 22:45 UTC, NRProjects commented
The special unicode character prevent it from building in IntelliJ

2023-12-30 22:46 UTC, NRProjects requested changes
Special unicode characters prevent it for building

2023-12-30 22:47 UTC, NRProjects commented on src/main/java/plugins/nate/smp/commands/SMPCommand.java
> +                    text.setText("ᴅᴇᴘᴏsɪᴛ ᴅɪᴀᴍᴏɴᴅs (Đ)");
Special unicode characters prevent it from building

2023-12-30 22:48 UTC, NRProjects requested changes
Re-reviewed the correct way

2023-12-30 22:58 UTC, NRProjects requested changes

2023-12-30 22:58 UTC, NRProjects commented on src/main/java/plugins/nate/smp/commands/SMPCommand.java
> +                    text.setText("ᴅᴇᴘᴏsɪᴛ ᴅɪᴀᴍᴏɴᴅs ("+ '\u00D0' + ")");
All characters are preventing it from building

2023-12-30 22:58 UTC, NRProjects commented on src/main/java/plugins/nate/smp/commands/SMPCommand.java
> +                    text.setText("ᴡɪᴛʜᴅʀᴀᴡ ᴅɪᴀᴍᴏɴᴅs ("+ '\u00D0' + ")");
All characters are preventing it from building

2023-12-31 01:53 UTC, paulpugh000 commented on src/main/java/plugins/nate/smp/commands/SMPCommand.java
> +                    text.setText("ᴡɪᴛʜᴅʀᴀᴡ ᴅɪᴀᴍᴏɴᴅs ("+ '\u00D0' + ")");
Can you post logs of what errors you are getting? Building with Gradle works perfectly fine for me.

2023-12-31 01:56 UTC, NRProjects approved these changes

2023-12-31 01:56 UTC, merged